# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft
minecraft_version=1.21.4
minecraft_version_range=[1.21.4]

# NeoForge
neo_version=21.4.145
neo_version_range=[21.4.121,21.5)
loader_version_range=[1,)

# Mod properties
mod_id=omniwheel
mod_name=OmniWheel
mod_license=MIT License
mod_version=1.1r
mod_group_id=de.artemis.omniwheel
mod_authors=DoomedArtemis
mod_description=Client-side radial quick-action menu with configurable wheels, profiles, shortcuts, and multiplayer-safe command and keybind access.
